name: Build

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false

      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
        build_type: [ Debug, Release ]
        std: [ 23 ]

    steps:
      - uses: actions/checkout@v4

      - name: Install opengl
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgl1-mesa-dev

      - name: Configure CMake
        run: |
          cmake -B ${{github.workspace}}/build \
                -DCMAKE_BUILD_TYPE=${{matrix.build_type}} \
                -DCMAKE_CXX_STANDARD=${{matrix.std}} \
                -DCMAKE_CXX_STANDARD_REQUIRED=ON \
                -S ${{github.workspace}} \

      - name: Build
        run: cmake --build ${{ github.workspace }}/build --config ${{ matrix.build_type }}
