name: Tests

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false

      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
        build_type: [ Release ]
        std: [ 23 ]

    steps:
      - uses: actions/checkout@v4

      - name: Install opengl
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgl1-mesa-dev

      - name: Configure CMake
        run: >
          cmake -B ${{ github.workspace }}/build
          -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
          -DCMAKE_CXX_STANDARD=${{ matrix.std }}
          -DCMAKE_CXX_STANDARD_REQUIRED=ON
          -S ${{ github.workspace }}

      - name: Build
        run: cmake --build ${{ github.workspace }}/build --config ${{ matrix.build_type }} --target Tests

      - name: Test
        env:
          CTEST_OUTPUT_ON_FAILURE: 1
        working-directory: ${{github.workspace}}/build
        run: ctest --build-config ${{matrix.build_type}} --debug --parallel `nproc`

      - uses: actions/upload-artifact@v4
        with:
          # Name of the artifact to upload.
          # Optional. Default is 'artifact'
          name: Timings-${{ matrix.os }}

          # A file, directory or wildcard pattern that describes what to upload
          # Required.
          path:  ${{ github.workspace }}/build/Tests/Data

          # Duration after which artifact will expire in days. 0 means using default retention.
          # Minimum 1 day.
          # Maximum 90 days unless changed from the repository settings page.
          # Optional. Defaults to repository settings.
          retention-days: 1